POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "TestTitle",
    "author": "TestName",
    "url": "some/test/url",
    "likes": "5"
}

###
http://localhost:3001/api/blogs

### Users

http://localhost:3001/api/users
